# Teena Bokde
# Data Science - Batch Oct 2024 (Pune) - Assignment 18
# Neural Networks

# Task 1: Data Exploration and Preprocessing

Importing necessary libraries

In [1]:
import pandas as pd

Loading the dataset

In [2]:
data = pd.read_csv("Alphabets_data.csv")

In [3]:
data

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

Displaying the first few rows of the dataset

In [ ]:
print(data.head())

  letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10  


Summary of the dataset

In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB
None


Checking for missing values

In [ ]:
print(data.isnull().sum())

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64


Statistical summary of numerical features

In [ ]:
print(data.describe())

               xbox          ybox         width       height         onpix  \
count  20000.000000  20000.000000  20000.000000  20000.00000  20000.000000   
mean       4.023550      7.035500      5.121850      5.37245      3.505850   
std        1.913212      3.304555      2.014573      2.26139      2.190458   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        3.000000      5.000000      4.000000      4.00000      2.000000   
50%        4.000000      7.000000      5.000000      6.00000      3.000000   
75%        5.000000      9.000000      6.000000      7.00000      5.000000   
max       15.000000     15.000000     15.000000     15.00000     15.000000   

               xbar          ybar         x2bar         y2bar         xybar  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.897600      7.500450      4.628600      5.178650      8.282050   
std        2.026035      2.325354      2.699968      2.38082

Checking the number of unique classes in the 'letter' column

In [ ]:
print(data['letter'].nunique())

26


In [ ]:
from sklearn.preprocessing import StandardScaler

Handling missing values (if any)

In [ ]:
data = data.dropna()

In [ ]:
data

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

Separating features and target variable

In [ ]:
X = data.drop('letter', axis=1)
y = data['letter']

In [ ]:
X

xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0         2     8      3       5      1     8    13      0      6      6   
1         5    12      3       7      2    10     5      5      4     13   
2         4    11      6       8      6    10     6      2      6     10   
3         7    11      6       6      3     5     9      4      6      4   
4         2     1      3       1      1     8     6      6      6      6   
...     ...   ...    ...     ...    ...   ...   ...    ...    ...    ...   
19995     2     2      3       3      2     7     7      7      6      6   
19996     7    10      8       8      4     4     8      6      9     12   
19997     6     9      6       7      5     6    11      3      7     11   
19998     2     3      4       2      1     8     7      2      6     10   
19999     4     9      6       6      2     9     5      3      1      8   

       x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          10       8      0       8      0       8  
1           3       9      2       8      4      10  
2           3       7      3       7      3       9  
3           4      10      6      10      2       8  
4           5       9      1       7      5      10  
...       ...     ...    ...     ...    ...     ...  
19995       6       4      2       8      3       7  
19996       9      13      2       9      3       7  
19997       9       5      2      12      2       4  
19998       6       8      1       9      5       8  
19999       1       8      2       7      2       8  

[20000 rows x 16 columns]

In [ ]:
y

0        T
1        I
2        D
3        N
4        G
        ..
19995    D
19996    C
19997    T
19998    S
19999    A
Name: letter, Length: 20000, dtype: object

Normalizing the numerical columns

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

In [ ]:
scaler

StandardScaler()

In [ ]:
X_normalized

array([[-1.0576983 ,  0.29187713, -1.05327668, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -1.05327668, ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.43590966, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -0.55688123, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727,  0.43590966, ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

Displaying the first few rows of normalized data

In [ ]:
print(pd.DataFrame(X_normalized, columns=X.columns).head())

       xbox      ybox     width    height     onpix      xbar      ybar  \
0 -1.057698  0.291877 -1.053277 -0.164704 -1.144013  0.544130  2.365097   
1  0.510385  1.502358 -1.053277  0.719730 -0.687476  1.531305 -1.075326   
2 -0.012309  1.199738  0.435910  1.161947  1.138672  1.531305 -0.645273   
3  1.555774  1.199738  0.435910  0.277513 -0.230939 -0.936631  0.644886   
4 -1.057698 -1.826464 -1.053277 -1.933571 -1.144013  0.544130 -0.645273   

      x2bar     y2bar     xybar    x2ybar    xy2bar     xedge    xedgey  \
0 -1.714360  0.344994 -0.917071  1.347774  0.034125 -1.305948 -0.219082   
1  0.137561 -0.495072  1.895968 -1.312807  0.514764 -0.448492 -0.219082   
2 -0.973591  0.344994  0.690380 -1.312807 -0.446513 -0.019764 -0.865626   
3 -0.232823  0.344994 -1.720796 -0.932724  0.995402  1.266419  1.074008   
4  0.507945  0.344994 -0.917071 -0.552641  0.514764 -0.877220 -0.865626   

      yedge    yedgex  
0 -1.438153  0.122911  
1  0.120081  1.359441  
2 -0.269477  0.741176  
3 

# Task 2: Model Implementation

Importing necessary libraries for neural network

In [ ]:
pip install scikeras

Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install --upgrade scikit-learn scikeras tensorflow

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

Encoding categorical target labels

In [ ]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [ ]:
label_encoder

LabelEncoder()

In [ ]:
y_encoded

array([19,  8,  3, ..., 19, 18,  0])

Convering encoded labels to categorical (one-hot encoding)

In [ ]:
y_categorical = to_categorical(y_encoded)
y_categorical

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

Splitting data into training and test sets

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y_categorical, test_size=0.2, random_state=42)
X_train

array([[-0.01230945, -0.01074302, -0.06048579, ..., -0.21908163,
         0.12008142,  0.12291107],
       [-0.01230945, -0.01074302,  0.43590966, ..., -0.21908163,
         0.12008142, -0.49535386],
       [-0.53500387, -0.6159833 , -0.55688123, ...,  0.42746295,
        -0.65903564, -1.11361878],
       ...,
       [-0.53500387, -0.91860345,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       [-0.53500387,  0.29187713, -0.55688123, ..., -0.21908163,
        -1.04859417, -0.49535386],
       [-1.58039272, -1.22122359, -1.54967212, ..., -0.8656262 ,
        -1.4381527 , -0.49535386]])

In [ ]:
X_test

array([[-0.53500387, -0.31336316, -0.06048579, ..., -0.8656262 ,
         1.288757  , -1.11361878],
       [-0.01230945,  1.19973756,  0.43590966, ...,  1.7205521 ,
         1.288757  , -1.73188371],
       [-0.53500387, -0.91860345, -0.06048579, ..., -1.51217078,
        -0.65903564,  0.12291107],
       ...,
       [ 0.51038497,  0.89711742,  0.93230511, ..., -0.21908163,
         0.12008142,  0.12291107],
       [-0.01230945, -0.6159833 , -0.06048579, ...,  1.07400752,
         2.06787406, -1.73188371],
       [-1.0576983 , -0.6159833 , -0.55688123, ...,  1.7205521 ,
        -0.65903564,  0.12291107]])

In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

Building a basic ANN model

In [ ]:
import warnings
warnings.filterwarnings('ignore')

model = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),  # input layer + first hidden layer
    Dense(32, activation='relu'),  # second hidden layer
    Dense(y_categorical.shape[1], activation='softmax')  # output layer
])

Compiling the model

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

Displaying the model summary

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 26)             │           858 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,026 (15.73 KB)

 Trainable params: 4,026 (15.73 KB)

 Non-trainable params: 0 (0.00 B)

Training the model

In [ ]:
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)
history

Epoch 1/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.2667 - loss: 2.6611 - val_accuracy: 0.6622 - val_loss: 1.2369
Epoch 2/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6928 - loss: 1.0894 - val_accuracy: 0.7406 - val_loss: 0.9111
Epoch 3/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7707 - loss: 0.8114 - val_accuracy: 0.7894 - val_loss: 0.7401
Epoch 4/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8055 - loss: 0.6789 - val_accuracy: 0.8144 - val_loss: 0.6435
Epoch 5/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8274 - loss: 0.5899 - val_accuracy: 0.8338 - val_loss: 0.5774
Epoch 6/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8474 - loss: 0.5251 - val_accuracy: 0.8466 - val_loss: 0.5313
Epoch 7/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8682 - loss: 0.4605 - val_accuracy: 0.8537 - val_loss: 0.4960
Epoch 8/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8732 - loss: 0.4260 - val_accuracy: 0.

Evaluating the model on the test set

In [ ]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {test_accuracy:.4f}')

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9169 - loss: 0.2622
Test Accuracy: 0.9172


Making predictions on the test set

In [ ]:
y_pred = model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=-1)
y_pred

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[1.29686327e-07, 3.18400112e-06, 3.77013052e-08, ...,
        2.92440593e-01, 8.48046420e-06, 6.75150990e-01],
       [5.60961373e-04, 3.22846725e-04, 3.45421094e-03, ...,
        1.75054627e-03, 9.52101487e-04, 4.35212314e-06],
       [9.99933004e-01, 4.85388080e-15, 4.25657908e-14, ...,
        1.08889054e-07, 5.07350468e-17, 5.23966460e-11],
       ...,
       [4.96079508e-07, 1.08136345e-15, 2.63928541e-07, ...,
        1.95724733e-05, 2.13933859e-07, 3.77710840e-08],
       [5.83001056e-05, 4.32248953e-06, 5.15036555e-11, ...,
        1.90870502e-04, 9.61717069e-01, 3.47911417e-02],
       [3.00185043e-10, 7.36470330e-15, 2.32804292e-12, ...,
        9.99795702e-06, 9.99003232e-01, 4.68766822e-12]], dtype=float32)

In [ ]:
y_pred_classes

array([25, 11,  0, ..., 16, 24, 24], dtype=int64)

Converting one-hot encoded labels back to integers

In [ ]:
y_test_classes = y_test.argmax(axis=-1)

In [ ]:
y_test_classes

array([19, 11,  0, ..., 16, 24, 24], dtype=int64)

# Task 3: Hyperparameter Tuning

In [ ]:
from sklearn.model_selection import GridSearchCV

Function to create model (for KerasClassifier)

In [ ]:
def create_model(optimizer='adam', activation='relu', neurons=32):
    model = Sequential()
    model.add(Dense(neurons, input_dim=X_train.shape[1], activation=activation))
    model.add(Dense(neurons, activation=activation))
    model.add(Dense(y_categorical.shape[1], activation='softmax'))
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

Creating a KerasClassifier

In [ ]:
import sklearn
import scikeras
import tensorflow as tf

print("scikit-learn version:", sklearn.__version__)
print("scikeras version:", scikeras.__version__)
print("tensorflow version:", tf.__version__)

scikit-learn version: 1.5.2
scikeras version: 0.13.0
tensorflow version: 2.17.0


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np

Function to create a model with specified hyperparameters

In [ ]:
def create_model(num_hidden_layers=1, neurons_per_layer=32, activation='relu', learning_rate=0.001):
    model = Sequential()
    model.add(Dense(neurons_per_layer, input_dim=X_train.shape[1], activation=activation))

    # Add hidden layers as specified
    for _ in range(num_hidden_layers - 1):
        model.add(Dense(neurons_per_layer, activation=activation))

    model.add(Dense(y_train.shape[1], activation='softmax'))  # Output layer

    # Compile the model
    optimizer = Adam(learning_rate=learning_rate)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

Hyperparameters to tune

In [ ]:
num_hidden_layers_options = [1, 2, 3]
neurons_per_layer_options = [32, 64, 128]
activation_options = ['relu', 'tanh']
learning_rate_options = [0.001, 0.01]

Splitting data into training and validation sets

In [ ]:
scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_normalized, y_categorical, test_size=0.2, random_state=42)

best_accuracy = 0
best_model = None
best_params = {}

# Manual grid search
for num_hidden_layers in num_hidden_layers_options:
    for neurons_per_layer in neurons_per_layer_options:
        for activation in activation_options:
            for learning_rate in learning_rate_options:
                print(f"Training model with {num_hidden_layers} hidden layers, {neurons_per_layer} neurons per layer, activation={activation}, learning_rate={learning_rate}")

                # Create and train the model
                model = create_model(num_hidden_layers, neurons_per_layer, activation, learning_rate)
                model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_val, y_val), verbose=0)

                # Evaluate the model
                val_loss, val_accuracy = model.evaluate(X_val, y_val, verbose=0)

                # Check if this model is the best one so far
                if val_accuracy > best_accuracy:
                    best_accuracy = val_accuracy
                    best_model = model
                    best_params = {
                        'num_hidden_layers': num_hidden_layers,
                        'neurons_per_layer': neurons_per_layer,
                        'activation': activation,
                        'learning_rate': learning_rate
                    }

print(f"Best model parameters: {best_params}")
print(f"Best validation accuracy: {best_accuracy:.4f}")

Training model with 1 hidden layers, 32 neurons per layer, activation=relu, learning_rate=0.001
Training model with 1 hidden layers, 32 neurons per layer, activation=relu, learning_rate=0.01
Training model with 1 hidden layers, 32 neurons per layer, activation=tanh, learning_rate=0.001
Training model with 1 hidden layers, 32 neurons per layer, activation=tanh, learning_rate=0.01
Training model with 1 hidden layers, 64 neurons per layer, activation=relu, learning_rate=0.001
Training model with 1 hidden layers, 64 neurons per layer, activation=relu, learning_rate=0.01
Training model with 1 hidden layers, 64 neurons per layer, activation=tanh, learning_rate=0.001
Training model with 1 hidden layers, 64 neurons per layer, activation=tanh, learning_rate=0.01
Training model with 1 hidden layers, 128 neurons per layer, activation=relu, learning_rate=0.001
Training model with 1 hidden layers, 128 neurons per layer, activation=relu, learning_rate=0.01
Training model with 1 hidden layers, 128 ne

# Task 4: Evaluation

In [ ]:
y_pred = best_model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


Calculating performance metrics

In [ ]:
accuracy = accuracy_score(y_test_classes, y_pred_classes)
precision = precision_score(y_test_classes, y_pred_classes, average='weighted')
recall = recall_score(y_test_classes, y_pred_classes, average='weighted')
f1 = f1_score(y_test_classes, y_pred_classes, average='weighted')

print(f"Test Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

Test Accuracy: 0.9640
Precision: 0.9644
Recall: 0.9640
F1-Score: 0.9640


# **Discuss the Performance Differences**

Now that I have trained both a default model and a tuned model, it's essential to analyze and understand the impact of hyperparameter tuning on the model's performance. I will evaluate the models based on accuracy, precision, recall, and F1-score.

Default vs. Tuned Model Performance
Default Model Performance:

The default model is typically set with a basic configuration of hyperparameters, such as:

Number of hidden layers: 1

Neurons per hidden layer: 32

Activation function: ReLU

Learning rate: 0.001

Performance Metrics:

Accuracy:

Indicates the proportion of correctly classified instances among the total number of instances.

Precision:

The ratio of true positive predictions to the total predicted positives (precision of how many predicted letters were actually correct).

Recall:

The ratio of true positive predictions to the actual positives (recall of how well the model detected the correct letters).

F1-Score:

The harmonic mean of precision and recall, providing a balanced measure of a model's performance.

Tuned Model Performance:

The tuned model has undergone hyperparameter optimization, adjusting parameters like the number of hidden layers, neurons per layer, activation functions, and learning rate.

Performance Improvements:

Accuracy:

Likely improved due to better parameter choices that more accurately map the input data to the correct output labels.

Precision and Recall:

Improved, indicating better overall prediction quality, including a reduction in false positives and false negatives.

F1-Score:

Higher, showing a more balanced improvement in precision and recall, meaning the model has become more robust in making correct predictions across all classes.